# Number of sequences to subsample for speed test.
SPEED_BENCHMARKS = [1,10,25,50,75,100]

rule all:
    input:
        benchmarks = expand( "intermediates/benchmarks/sample{sample}-trail{trial}.tsv", sample=SPEED_BENCHMARKS, trial=range(3) ),
        benchmark_summary = "results/benchmark-summary.csv",
        benchmark_plot = "results/plots/speed-memory-benchmark.pdf",
        accuracy_lineage_calls = "intermediates/accuracy_runs/lineage_report.csv",
        accuracy_plot= "results/plots/accuracy-confusion-matrix.pdf",
        parsimony_plot= "results/plots/parsimoneous-placements.pdf",
        masking_results = "results/usher-masking.csv",
        accuracy_masking_plot= "results/plots/accuracy-vs-masking.pdf",
        parsimony_masking_plot= "results/plots/parsimony-vs-masking.pdf",
        variant_masking_results = "results/usher-variant-masking.csv"
        #freyja_masking = "results/freyja_masking.csv"

include: "rules/benchmarks.smk"
include: "rules/usher_masking.smk"
