name: london
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - usher
  - biopython
  - minimap2=2.28
  - rich
  - gofasta
  - pandas
  - freyja
  - bcftools
  - samtools
  - seqtk
  - pytest
  - pyarrow